"""Summarise the recorded traffic-camera data and draw two charts.

Reads data/live_observations.jsonl (one JSON object per camera reading) and
writes, to data/charts/:

    summary.md           coverage and traffic statistics, as tables
    coverage.svg         readings per hour across the whole recording
    traffic_by_hour.svg  average vehicles per reading, by hour of day (London)

Standard library only, so it runs with the project's normal install:

    python scripts/data_summary.py
    python scripts/data_summary.py --data path/to/live_observations.jsonl
"""
from __future__ import annotations

import argparse
import json
import statistics
from collections import Counter, defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parent.parent
LONDON = ZoneInfo("Europe/London")

# A gap longer than this between consecutive readings counts as a break in
# collection (the collectors sweep every 6 minutes).
BREAK = timedelta(minutes=30)

# The engine only trusts "share of vehicles moving" when it tracked at least
# this many vehicles (MIN_TRACKS_FOR_STALL in route_engine/live_engine.py).
MIN_TRACKS = 2


def load(path: Path):
    rows, bad = [], 0
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            if not line.strip():
                continue
            try:
                rows.append(json.loads(line))
            except ValueError:
                bad += 1          # e.g. a line cut short when a collector was stopped
    rows.sort(key=lambda r: r["t_wall"])
    return rows, bad


def london(t: float) -> datetime:
    return datetime.fromtimestamp(t, tz=timezone.utc).astimezone(LONDON)


def runs(times):
    """Unbroken stretches of collection, as (start, end) datetimes."""
    out, start, prev = [], times[0], times[0]
    for t in times[1:]:
        if t - prev > BREAK:
            out.append((start, prev))
            start = t
        prev = t
    out.append((start, prev))
    return out


def summarise(rows, bad):
    times = [london(r["t_wall"]) for r in rows]
    per_cam = Counter(r["camera_id"] for r in rows)
    stretches = runs(times)
    longest = max(stretches, key=lambda s: s[1] - s[0])

    by_hour = defaultdict(list)          # hour of day (London) -> readings
    for r, t in zip(rows, times):
        by_hour[t.hour].append(r)

    classes = Counter()
    for r in rows:
        classes.update(r.get("classes") or {})
    total = sum(classes.values()) or 1

    moving = [r["moving_frac"] for r in rows if r.get("tracks", 0) >= MIN_TRACKS]

    return {
        "readings": len(rows), "bad_lines": bad,
        "cameras": len(per_cam),
        "per_cam": sorted(per_cam.values()),
        "first": times[0], "last": times[-1],
        "stretches": stretches, "longest": longest,
        "days": Counter(t.strftime("%a %d %b") for t in times),
        "weekday_share": sum(t.weekday() < 5 for t in times) / len(times),
        "mean_vehicles": statistics.fmean(r["count_mean"] for r in rows),
        "median_moving": statistics.median(moving) if moving else None,
        "mean_moving": statistics.fmean(moving) if moving else None,
        "classes": {k: v / total for k, v in classes.most_common()},
        "by_hour": {h: (len(v), statistics.fmean(x["count_mean"] for x in v))
                    for h, v in sorted(by_hour.items())},
        "hourly_counts": Counter(t.replace(minute=0, second=0, microsecond=0) for t in times),
    }


def fmt(t: datetime) -> str:
    return t.strftime("%a %d %b %H:%M")


def write_markdown(s, out: Path, source: Path):
    hrs = lambda a, b: (b - a).total_seconds() / 3600
    pc = s["per_cam"]
    lines = [
        "# Recorded traffic data: summary",
        "",
        "Generated by `scripts/data_summary.py` from `%s`. Times are London time." % source.name,
        "",
        "| | |", "|---|---|",
        "| Camera readings | %s |" % f"{s['readings']:,}",
        "| Unreadable lines skipped | %d |" % s["bad_lines"],
        "| Cameras | %d |" % s["cameras"],
        "| Readings per camera | min %d, median %d, max %d |" % (pc[0], pc[len(pc) // 2], pc[-1]),
        "| First reading | %s |" % fmt(s["first"]),
        "| Last reading | %s |" % fmt(s["last"]),
        "| Span | %.1f hours |" % hrs(s["first"], s["last"]),
        "| Hours actually collected | %.1f (in %d separate stretches) |"
        % (sum(hrs(a, b) for a, b in s["stretches"]), len(s["stretches"])),
        "| Longest unbroken stretch | %.1f hours (%s to %s) |"
        % (hrs(*s["longest"]), fmt(s["longest"][0]), fmt(s["longest"][1])),
        "| Readings on weekdays | %.0f%% |" % (100 * s["weekday_share"]),
        "| Average vehicles per reading | %.1f |" % s["mean_vehicles"],
        "| Share of vehicles moving (readings with %d+ tracked) | %s |"
        % (MIN_TRACKS, "average %.0f%%, median %.0f%%" % (100 * s["mean_moving"], 100 * s["median_moving"])
           if s["mean_moving"] is not None else "n/a"),
        "",
        "## Readings per day", "", "| Day | Readings |", "|---|---|",
        *("| %s | %s |" % (d, f"{n:,}") for d, n in s["days"].items()),
        "",
        "## Vehicle types (share of all detections)", "", "| Type | Share |", "|---|---|",
        *("| %s | %.1f%% |" % (k, 100 * v) for k, v in s["classes"].items()),
        "",
        "## By hour of day", "", "| Hour | Readings | Avg vehicles per reading |", "|---|---|---|",
        *("| %02d:00 | %s | %.1f |" % (h, f"{n:,}", m) for h, (n, m) in s["by_hour"].items()),
        "",
        "![Readings per hour](coverage.svg)", "",
        "![Average vehicles by hour of day](traffic_by_hour.svg)", "",
    ]
    (out / "summary.md").write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# Charts: plain SVG, one series each, light and dark themes built in.
# ---------------------------------------------------------------------------

STYLE = """<style>
  .bg{fill:#fcfcfb} .bar{fill:#2a78d6} .grid{stroke:#e4e3df;stroke-width:1}
  .t{fill:#0b0b0b;font:600 15px system-ui,sans-serif}
  .s,.ax{fill:#52514e;font:12px system-ui,sans-serif}
  @media (prefers-color-scheme:dark){
    .bg{fill:#1a1a19} .bar{fill:#3987e5} .grid{stroke:#383835}
    .t{fill:#ffffff} .s,.ax{fill:#c3c2b7}
  }
</style>"""


def column(x, y, w, h, radius=4.0):
    """A column with a rounded top and a square base."""
    r = min(radius, w / 2, h)
    return ("M%.1f,%.1f v%.1f a%.1f,%.1f 0 0 1 %.1f,%.1f h%.1f a%.1f,%.1f 0 0 1 %.1f,%.1f v%.1f z"
            % (x, y + h, -(h - r), r, r, r, -r, w - 2 * r, r, r, r, r, h - r))


def nice_max(v):
    for step in (1, 2, 2.5, 5, 10, 20, 25, 50, 100, 200, 250, 500, 1000):
        if v <= step * 4:
            return step * 4, step
    return v, v / 4


def svg_columns(values, labels, tips, title, subtitle, path: Path):
    W, H, L, R, T, B = 760, 320, 48, 16, 64, 40
    pw, ph = W - L - R, H - T - B
    top, step = nice_max(max(values) if values else 1)
    slot = pw / max(len(values), 1)
    bw = min(24.0, max(slot - 2, 1.0))          # 2px surface gap between columns
    out = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" role="img" '
           'aria-label="%s">' % (W, H, title), STYLE,
           '<rect class="bg" width="%d" height="%d"/>' % (W, H),
           '<text class="t" x="%d" y="24">%s</text>' % (L, title),
           '<text class="s" x="%d" y="44">%s</text>' % (L, subtitle)]
    tick = 0.0
    while tick <= top + 1e-9:
        y = T + ph - ph * tick / top
        out.append('<line class="grid" x1="%d" x2="%d" y1="%.1f" y2="%.1f"/>' % (L, W - R, y, y))
        out.append('<text class="ax" x="%d" y="%.1f" text-anchor="end">%s</text>'
                   % (L - 6, y + 4, f"{tick:,.0f}" if step >= 1 else f"{tick:g}"))
        tick += step
    for i, (v, lab, tip) in enumerate(zip(values, labels, tips)):
        x = L + i * slot + (slot - bw) / 2
        h = ph * v / top
        if h > 0:
            out.append('<path class="bar" d="%s"><title>%s</title></path>'
                       % (column(x, T + ph - h, bw, h), tip))
        if lab:                                   # blank label = no tick text
            out.append('<text class="ax" x="%.1f" y="%d" text-anchor="middle">%s</text>'
                       % (x + bw / 2, H - 18, lab))
    out.append("</svg>")
    path.write_text("\n".join(out), encoding="utf-8")


def charts(s, out: Path):
    # 1. Coverage: every clock hour from first to last reading, gaps included.
    start = s["first"].replace(minute=0, second=0, microsecond=0)
    hours, t = [], start
    while t <= s["last"]:
        hours.append(t)
        t += timedelta(hours=1)
    counts = [s["hourly_counts"].get(h, 0) for h in hours]
    day_labels = [h.strftime("%a %d") if h.hour == 0 or i == 0 else "" for i, h in enumerate(hours)]
    svg_columns(
        counts, day_labels,
        ["%s: %d readings" % (h.strftime("%a %d %b %H:00"), n) for h, n in zip(hours, counts)],
        "Camera readings per hour",
        "Each column is one hour (London time). Empty stretches are times the collectors were not running.",
        out / "coverage.svg")
    # 2. Traffic by hour of day: all 24 hours, so an hour with no data shows
    #    as an empty slot instead of silently closing up the axis.
    svg_columns(
        [s["by_hour"].get(h, (0, 0.0))[1] for h in range(24)],
        ["%02d" % h if h % 2 == 0 else "" for h in range(24)],
        ["%02d:00: %.1f vehicles per reading" % (h, s["by_hour"][h][1]) if h in s["by_hour"]
         else "%02d:00: no data" % h for h in range(24)],
        "Average vehicles per camera reading, by hour of day",
        "London time. Empty slots are hours with no recorded data; summary.md lists readings per hour.",
        out / "traffic_by_hour.svg")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--data", type=Path, default=ROOT / "data" / "live_observations.jsonl")
    ap.add_argument("--out", type=Path, default=ROOT / "data" / "charts")
    args = ap.parse_args()

    rows, bad = load(args.data)
    if not rows:
        raise SystemExit("No readings found in %s" % args.data)
    s = summarise(rows, bad)
    args.out.mkdir(parents=True, exist_ok=True)
    write_markdown(s, args.out, args.data)
    charts(s, args.out)
    print((args.out / "summary.md").read_text(encoding="utf-8").split("## Readings per day")[0])
    print("Wrote summary.md, coverage.svg and traffic_by_hour.svg to %s" % args.out)


if __name__ == "__main__":
    main()
